// Code generated by "stringer -type=Code -output errors_generated.go"; DO NOT EDIT.

package errors

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownError-0]
	_ = x[InvalidArgument-1]
	_ = x[OutOfRange-2]
	_ = x[NotFound-3]
	_ = x[InvalidValue-4]
	_ = x[InvalidSettings-5]
	_ = x[Handler-6]
	_ = x[TypeCast-7]
	_ = x[TypeCoerce-8]
	_ = x[Jsonify-9]
}

const _Code_name = "UnknownErrorInvalidArgumentOutOfRangeNotFoundInvalidValueInvalidSettingsHandlerTypeCastTypeCoerceJsonify"

var _Code_index = [...]uint8{0, 12, 27, 37, 45, 57, 72, 79, 87, 97, 104}

func (i Code) String() string {
	if i < 0 || i >= Code(len(_Code_index)-1) {
		return "Code(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Code_name[_Code_index[i]:_Code_index[i+1]]
}
