// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: origin.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MethodType int32

const (
	MethodType_GET  MethodType = 0
	MethodType_POST MethodType = 1
)

// Enum value maps for MethodType.
var (
	MethodType_name = map[int32]string{
		0: "GET",
		1: "POST",
	}
	MethodType_value = map[string]int32{
		"GET":  0,
		"POST": 1,
	}
)

func (x MethodType) Enum() *MethodType {
	p := new(MethodType)
	*p = x
	return p
}

func (x MethodType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MethodType) Descriptor() protoreflect.EnumDescriptor {
	return file_origin_proto_enumTypes[0].Descriptor()
}

func (MethodType) Type() protoreflect.EnumType {
	return &file_origin_proto_enumTypes[0]
}

func (x MethodType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MethodType.Descriptor instead.
func (MethodType) EnumDescriptor() ([]byte, []int) {
	return file_origin_proto_rawDescGZIP(), []int{0}
}

// Part of url.
type Value_Url_Part int32

const (
	Value_Url_SCHEME    Value_Url_Part = 0
	Value_Url_AUTHORITY Value_Url_Part = 1
	Value_Url_HOST      Value_Url_Part = 2
	Value_Url_PORT      Value_Url_Part = 3
	Value_Url_PATH      Value_Url_Part = 4
	Value_Url_QUERY     Value_Url_Part = 5
	Value_Url_FRAGMENT  Value_Url_Part = 6
	Value_Url_ALL       Value_Url_Part = 7
)

// Enum value maps for Value_Url_Part.
var (
	Value_Url_Part_name = map[int32]string{
		0: "SCHEME",
		1: "AUTHORITY",
		2: "HOST",
		3: "PORT",
		4: "PATH",
		5: "QUERY",
		6: "FRAGMENT",
		7: "ALL",
	}
	Value_Url_Part_value = map[string]int32{
		"SCHEME":    0,
		"AUTHORITY": 1,
		"HOST":      2,
		"PORT":      3,
		"PATH":      4,
		"QUERY":     5,
		"FRAGMENT":  6,
		"ALL":       7,
	}
)

func (x Value_Url_Part) Enum() *Value_Url_Part {
	p := new(Value_Url_Part)
	*p = x
	return p
}

func (x Value_Url_Part) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Value_Url_Part) Descriptor() protoreflect.EnumDescriptor {
	return file_origin_proto_enumTypes[1].Descriptor()
}

func (Value_Url_Part) Type() protoreflect.EnumType {
	return &file_origin_proto_enumTypes[1]
}

func (x Value_Url_Part) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Value_Url_Part.Descriptor instead.
func (Value_Url_Part) EnumDescriptor() ([]byte, []int) {
	return file_origin_proto_rawDescGZIP(), []int{0, 2, 0}
}

type Value_Util_Now_Type int32

const (
	Value_Util_Now_TIMESTAMP Value_Util_Now_Type = 0
)

// Enum value maps for Value_Util_Now_Type.
var (
	Value_Util_Now_Type_name = map[int32]string{
		0: "TIMESTAMP",
	}
	Value_Util_Now_Type_value = map[string]int32{
		"TIMESTAMP": 0,
	}
)

func (x Value_Util_Now_Type) Enum() *Value_Util_Now_Type {
	p := new(Value_Util_Now_Type)
	*p = x
	return p
}

func (x Value_Util_Now_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Value_Util_Now_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_origin_proto_enumTypes[2].Descriptor()
}

func (Value_Util_Now_Type) Type() protoreflect.EnumType {
	return &file_origin_proto_enumTypes[2]
}

func (x Value_Util_Now_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Value_Util_Now_Type.Descriptor instead.
func (Value_Util_Now_Type) EnumDescriptor() ([]byte, []int) {
	return file_origin_proto_rawDescGZIP(), []int{0, 3, 0, 0}
}

type Value_Util_Random_Type int32

const (
	Value_Util_Random_UUID Value_Util_Random_Type = 0
	// standard uniform distribution
	Value_Util_Random_STDU Value_Util_Random_Type = 1
)

// Enum value maps for Value_Util_Random_Type.
var (
	Value_Util_Random_Type_name = map[int32]string{
		0: "UUID",
		1: "STDU",
	}
	Value_Util_Random_Type_value = map[string]int32{
		"UUID": 0,
		"STDU": 1,
	}
)

func (x Value_Util_Random_Type) Enum() *Value_Util_Random_Type {
	p := new(Value_Util_Random_Type)
	*p = x
	return p
}

func (x Value_Util_Random_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Value_Util_Random_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_origin_proto_enumTypes[3].Descriptor()
}

func (Value_Util_Random_Type) Type() protoreflect.EnumType {
	return &file_origin_proto_enumTypes[3]
}

func (x Value_Util_Random_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Value_Util_Random_Type.Descriptor instead.
func (Value_Util_Random_Type) EnumDescriptor() ([]byte, []int) {
	return file_origin_proto_rawDescGZIP(), []int{0, 3, 1, 0}
}

type Value_Add_Type int32

const (
	// As string.
	Value_Add_STRING Value_Add_Type = 0
	// As number.
	Value_Add_NUMBER Value_Add_Type = 1
)

// Enum value maps for Value_Add_Type.
var (
	Value_Add_Type_name = map[int32]string{
		0: "STRING",
		1: "NUMBER",
	}
	Value_Add_Type_value = map[string]int32{
		"STRING": 0,
		"NUMBER": 1,
	}
)

func (x Value_Add_Type) Enum() *Value_Add_Type {
	p := new(Value_Add_Type)
	*p = x
	return p
}

func (x Value_Add_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Value_Add_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_origin_proto_enumTypes[4].Descriptor()
}

func (Value_Add_Type) Type() protoreflect.EnumType {
	return &file_origin_proto_enumTypes[4]
}

func (x Value_Add_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Value_Add_Type.Descriptor instead.
func (Value_Add_Type) EnumDescriptor() ([]byte, []int) {
	return file_origin_proto_rawDescGZIP(), []int{0, 4, 0}
}

type Value_Cast_Type int32

const (
	Value_Cast_BOOL   Value_Cast_Type = 0
	Value_Cast_NUMBER Value_Cast_Type = 1
	Value_Cast_STRING Value_Cast_Type = 2
)

// Enum value maps for Value_Cast_Type.
var (
	Value_Cast_Type_name = map[int32]string{
		0: "BOOL",
		1: "NUMBER",
		2: "STRING",
	}
	Value_Cast_Type_value = map[string]int32{
		"BOOL":   0,
		"NUMBER": 1,
		"STRING": 2,
	}
)

func (x Value_Cast_Type) Enum() *Value_Cast_Type {
	p := new(Value_Cast_Type)
	*p = x
	return p
}

func (x Value_Cast_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Value_Cast_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_origin_proto_enumTypes[5].Descriptor()
}

func (Value_Cast_Type) Type() protoreflect.EnumType {
	return &file_origin_proto_enumTypes[5]
}

func (x Value_Cast_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Value_Cast_Type.Descriptor instead.
func (Value_Cast_Type) EnumDescriptor() ([]byte, []int) {
	return file_origin_proto_rawDescGZIP(), []int{0, 5, 0}
}

type Template_Type int32

const (
	// Into body.
	Template_BODY Template_Type = 0
	// Into headers.
	Template_HEADER Template_Type = 1
)

// Enum value maps for Template_Type.
var (
	Template_Type_name = map[int32]string{
		0: "BODY",
		1: "HEADER",
	}
	Template_Type_value = map[string]int32{
		"BODY":   0,
		"HEADER": 1,
	}
)

func (x Template_Type) Enum() *Template_Type {
	p := new(Template_Type)
	*p = x
	return p
}

func (x Template_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Template_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_origin_proto_enumTypes[6].Descriptor()
}

func (Template_Type) Type() protoreflect.EnumType {
	return &file_origin_proto_enumTypes[6]
}

func (x Template_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Template_Type.Descriptor instead.
func (Template_Type) EnumDescriptor() ([]byte, []int) {
	return file_origin_proto_rawDescGZIP(), []int{1, 0}
}

type Action_TemplateType int32

const (
	// Exclude original request/response.
	Action_SELECT Action_TemplateType = 0
	// Append template values to original request/response.
	Action_APPEND Action_TemplateType = 1
)

// Enum value maps for Action_TemplateType.
var (
	Action_TemplateType_name = map[int32]string{
		0: "SELECT",
		1: "APPEND",
	}
	Action_TemplateType_value = map[string]int32{
		"SELECT": 0,
		"APPEND": 1,
	}
)

func (x Action_TemplateType) Enum() *Action_TemplateType {
	p := new(Action_TemplateType)
	*p = x
	return p
}

func (x Action_TemplateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action_TemplateType) Descriptor() protoreflect.EnumDescriptor {
	return file_origin_proto_enumTypes[7].Descriptor()
}

func (Action_TemplateType) Type() protoreflect.EnumType {
	return &file_origin_proto_enumTypes[7]
}

func (x Action_TemplateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action_TemplateType.Descriptor instead.
func (Action_TemplateType) EnumDescriptor() ([]byte, []int) {
	return file_origin_proto_rawDescGZIP(), []int{2, 0}
}

type Value struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Value:
	//	*Value_Null
	//	*Value_B
	//	*Value_N
	//	*Value_S
	//	*Value_L
	//	*Value_M
	//	*Value_Header_
	//	*Value_Body_
	//	*Value_Url_
	//	*Value_Util_
	//	*Value_Add_
	//	*Value_Cast_
	Value isValue_Value `protobuf_oneof:"value"`
}

func (x *Value) Reset() {
	*x = Value{}
	if protoimpl.UnsafeEnabled {
		mi := &file_origin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_origin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_origin_proto_rawDescGZIP(), []int{0}
}

func (m *Value) GetValue() isValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *Value) GetNull() structpb.NullValue {
	if x, ok := x.GetValue().(*Value_Null); ok {
		return x.Null
	}
	return structpb.NullValue(0)
}

func (x *Value) GetB() bool {
	if x, ok := x.GetValue().(*Value_B); ok {
		return x.B
	}
	return false
}

func (x *Value) GetN() float64 {
	if x, ok := x.GetValue().(*Value_N); ok {
		return x.N
	}
	return 0
}

func (x *Value) GetS() string {
	if x, ok := x.GetValue().(*Value_S); ok {
		return x.S
	}
	return ""
}

func (x *Value) GetL() *Value_List {
	if x, ok := x.GetValue().(*Value_L); ok {
		return x.L
	}
	return nil
}

func (x *Value) GetM() *Value_Map {
	if x, ok := x.GetValue().(*Value_M); ok {
		return x.M
	}
	return nil
}

func (x *Value) GetHeader() *Value_Header {
	if x, ok := x.GetValue().(*Value_Header_); ok {
		return x.Header
	}
	return nil
}

func (x *Value) GetBody() *Value_Body {
	if x, ok := x.GetValue().(*Value_Body_); ok {
		return x.Body
	}
	return nil
}

func (x *Value) GetUrl() *Value_Url {
	if x, ok := x.GetValue().(*Value_Url_); ok {
		return x.Url
	}
	return nil
}

func (x *Value) GetUtil() *Value_Util {
	if x, ok := x.GetValue().(*Value_Util_); ok {
		return x.Util
	}
	return nil
}

func (x *Value) GetAdd() *Value_Add {
	if x, ok := x.GetValue().(*Value_Add_); ok {
		return x.Add
	}
	return nil
}

func (x *Value) GetCast() *Value_Cast {
	if x, ok := x.GetValue().(*Value_Cast_); ok {
		return x.Cast
	}
	return nil
}

type isValue_Value interface {
	isValue_Value()
}

type Value_Null struct {
	Null structpb.NullValue `protobuf:"varint,100,opt,name=null,proto3,enum=google.protobuf.NullValue,oneof"`
}

type Value_B struct {
	B bool `protobuf:"varint,101,opt,name=b,proto3,oneof"`
}

type Value_N struct {
	N float64 `protobuf:"fixed64,102,opt,name=n,proto3,oneof"`
}

type Value_S struct {
	S string `protobuf:"bytes,103,opt,name=s,proto3,oneof"`
}

type Value_L struct {
	L *Value_List `protobuf:"bytes,104,opt,name=l,proto3,oneof"`
}

type Value_M struct {
	M *Value_Map `protobuf:"bytes,105,opt,name=m,proto3,oneof"`
}

type Value_Header_ struct {
	Header *Value_Header `protobuf:"bytes,106,opt,name=header,proto3,oneof"`
}

type Value_Body_ struct {
	Body *Value_Body `protobuf:"bytes,107,opt,name=body,proto3,oneof"`
}

type Value_Url_ struct {
	Url *Value_Url `protobuf:"bytes,108,opt,name=url,proto3,oneof"`
}

type Value_Util_ struct {
	Util *Value_Util `protobuf:"bytes,109,opt,name=util,proto3,oneof"`
}

type Value_Add_ struct {
	Add *Value_Add `protobuf:"bytes,110,opt,name=add,proto3,oneof"`
}

type Value_Cast_ struct {
	Cast *Value_Cast `protobuf:"bytes,111,opt,name=cast,proto3,oneof"`
}

func (*Value_Null) isValue_Value() {}

func (*Value_B) isValue_Value() {}

func (*Value_N) isValue_Value() {}

func (*Value_S) isValue_Value() {}

func (*Value_L) isValue_Value() {}

func (*Value_M) isValue_Value() {}

func (*Value_Header_) isValue_Value() {}

func (*Value_Body_) isValue_Value() {}

func (*Value_Url_) isValue_Value() {}

func (*Value_Util_) isValue_Value() {}

func (*Value_Add_) isValue_Value() {}

func (*Value_Cast_) isValue_Value() {}

// Request/Response data to Request/Response data mapper.
type Template struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  Template_Type `protobuf:"varint,101,opt,name=type,proto3,enum=jsonhttp.Template_Type" json:"type,omitempty"`
	Value *Value        `protobuf:"bytes,102,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Template) Reset() {
	*x = Template{}
	if protoimpl.UnsafeEnabled {
		mi := &file_origin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Template) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Template) ProtoMessage() {}

func (x *Template) ProtoReflect() protoreflect.Message {
	mi := &file_origin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Template.ProtoReflect.Descriptor instead.
func (*Template) Descriptor() ([]byte, []int) {
	return file_origin_proto_rawDescGZIP(), []int{1}
}

func (x *Template) GetType() Template_Type {
	if x != nil {
		return x.Type
	}
	return Template_BODY
}

func (x *Template) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

// What the Handler does.
type Action struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Action:
	//	*Action_Return_
	//	*Action_Gateway_
	Action isAction_Action `protobuf_oneof:"action"`
}

func (x *Action) Reset() {
	*x = Action{}
	if protoimpl.UnsafeEnabled {
		mi := &file_origin_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_origin_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_origin_proto_rawDescGZIP(), []int{2}
}

func (m *Action) GetAction() isAction_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func (x *Action) GetReturn() *Action_Return {
	if x, ok := x.GetAction().(*Action_Return_); ok {
		return x.Return
	}
	return nil
}

func (x *Action) GetGateway() *Action_Gateway {
	if x, ok := x.GetAction().(*Action_Gateway_); ok {
		return x.Gateway
	}
	return nil
}

type isAction_Action interface {
	isAction_Action()
}

type Action_Return_ struct {
	Return *Action_Return `protobuf:"bytes,101,opt,name=return,proto3,oneof"`
}

type Action_Gateway_ struct {
	Gateway *Action_Gateway `protobuf:"bytes,102,opt,name=gateway,proto3,oneof"`
}

func (*Action_Return_) isAction_Action() {}

func (*Action_Gateway_) isAction_Action() {}

type Handler struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path       string     `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	MethodType MethodType `protobuf:"varint,2,opt,name=methodType,proto3,enum=jsonhttp.MethodType" json:"methodType,omitempty"`
	Action     *Action    `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
}

func (x *Handler) Reset() {
	*x = Handler{}
	if protoimpl.UnsafeEnabled {
		mi := &file_origin_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Handler) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Handler) ProtoMessage() {}

func (x *Handler) ProtoReflect() protoreflect.Message {
	mi := &file_origin_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Handler.ProtoReflect.Descriptor instead.
func (*Handler) Descriptor() ([]byte, []int) {
	return file_origin_proto_rawDescGZIP(), []int{3}
}

func (x *Handler) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Handler) GetMethodType() MethodType {
	if x != nil {
		return x.MethodType
	}
	return MethodType_GET
}

func (x *Handler) GetAction() *Action {
	if x != nil {
		return x.Action
	}
	return nil
}

type Server struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Port     int32      `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	Handlers []*Handler `protobuf:"bytes,2,rep,name=handlers,proto3" json:"handlers,omitempty"`
}

func (x *Server) Reset() {
	*x = Server{}
	if protoimpl.UnsafeEnabled {
		mi := &file_origin_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_origin_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_origin_proto_rawDescGZIP(), []int{4}
}

func (x *Server) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Server) GetHandlers() []*Handler {
	if x != nil {
		return x.Handlers
	}
	return nil
}

// Value template based on request headers.
type Value_Header struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Header name.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *Value_Header) Reset() {
	*x = Value_Header{}
	if protoimpl.UnsafeEnabled {
		mi := &file_origin_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Value_Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value_Header) ProtoMessage() {}

func (x *Value_Header) ProtoReflect() protoreflect.Message {
	mi := &file_origin_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value_Header.ProtoReflect.Descriptor instead.
func (*Value_Header) Descriptor() ([]byte, []int) {
	return file_origin_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Value_Header) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// Value template based on request body.
type Value_Body struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Like js property accessor.
	//
	// # Example
	//
	// When body is below:
	//
	//     {
	//       "top": {
	//         "internal": "depth"
	//       }
	//     }
	//
	// and keys is ["top", "internal"], then get "depth".
	Keys []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *Value_Body) Reset() {
	*x = Value_Body{}
	if protoimpl.UnsafeEnabled {
		mi := &file_origin_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Value_Body) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value_Body) ProtoMessage() {}

func (x *Value_Body) ProtoReflect() protoreflect.Message {
	mi := &file_origin_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value_Body.ProtoReflect.Descriptor instead.
func (*Value_Body) Descriptor() ([]byte, []int) {
	return file_origin_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Value_Body) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

// Value template based on request url.
type Value_Url struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Value:
	//	*Value_Url_Part_
	//	*Value_Url_Query_
	//	*Value_Url_Path_
	Value isValue_Url_Value `protobuf_oneof:"value"`
}

func (x *Value_Url) Reset() {
	*x = Value_Url{}
	if protoimpl.UnsafeEnabled {
		mi := &file_origin_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Value_Url) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value_Url) ProtoMessage() {}

func (x *Value_Url) ProtoReflect() protoreflect.Message {
	mi := &file_origin_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value_Url.ProtoReflect.Descriptor instead.
func (*Value_Url) Descriptor() ([]byte, []int) {
	return file_origin_proto_rawDescGZIP(), []int{0, 2}
}

func (m *Value_Url) GetValue() isValue_Url_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *Value_Url) GetPart() Value_Url_Part {
	if x, ok := x.GetValue().(*Value_Url_Part_); ok {
		return x.Part
	}
	return Value_Url_SCHEME
}

func (x *Value_Url) GetQuery() *Value_Url_Query {
	if x, ok := x.GetValue().(*Value_Url_Query_); ok {
		return x.Query
	}
	return nil
}

func (x *Value_Url) GetPath() *Value_Url_Path {
	if x, ok := x.GetValue().(*Value_Url_Path_); ok {
		return x.Path
	}
	return nil
}

type isValue_Url_Value interface {
	isValue_Url_Value()
}

type Value_Url_Part_ struct {
	Part Value_Url_Part `protobuf:"varint,101,opt,name=part,proto3,enum=jsonhttp.Value_Url_Part,oneof"`
}

type Value_Url_Query_ struct {
	Query *Value_Url_Query `protobuf:"bytes,102,opt,name=query,proto3,oneof"`
}

type Value_Url_Path_ struct {
	Path *Value_Url_Path `protobuf:"bytes,103,opt,name=path,proto3,oneof"`
}

func (*Value_Url_Part_) isValue_Url_Value() {}

func (*Value_Url_Query_) isValue_Url_Value() {}

func (*Value_Url_Path_) isValue_Url_Value() {}

// Value template utilities.
type Value_Util struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Value:
	//	*Value_Util_Now_
	//	*Value_Util_Random_
	Value isValue_Util_Value `protobuf_oneof:"value"`
}

func (x *Value_Util) Reset() {
	*x = Value_Util{}
	if protoimpl.UnsafeEnabled {
		mi := &file_origin_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Value_Util) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value_Util) ProtoMessage() {}

func (x *Value_Util) ProtoReflect() protoreflect.Message {
	mi := &file_origin_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value_Util.ProtoReflect.Descriptor instead.
func (*Value_Util) Descriptor() ([]byte, []int) {
	return file_origin_proto_rawDescGZIP(), []int{0, 3}
}

func (m *Value_Util) GetValue() isValue_Util_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *Value_Util) GetNow() *Value_Util_Now {
	if x, ok := x.GetValue().(*Value_Util_Now_); ok {
		return x.Now
	}
	return nil
}

func (x *Value_Util) GetRandom() *Value_Util_Random {
	if x, ok := x.GetValue().(*Value_Util_Random_); ok {
		return x.Random
	}
	return nil
}

type isValue_Util_Value interface {
	isValue_Util_Value()
}

type Value_Util_Now_ struct {
	Now *Value_Util_Now `protobuf:"bytes,101,opt,name=now,proto3,oneof"`
}

type Value_Util_Random_ struct {
	Random *Value_Util_Random `protobuf:"bytes,102,opt,name=random,proto3,oneof"`
}

func (*Value_Util_Now_) isValue_Util_Value() {}

func (*Value_Util_Random_) isValue_Util_Value() {}

// Add up values.
type Value_Add struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type   Value_Add_Type `protobuf:"varint,101,opt,name=type,proto3,enum=jsonhttp.Value_Add_Type" json:"type,omitempty"`
	Values []*Value       `protobuf:"bytes,102,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *Value_Add) Reset() {
	*x = Value_Add{}
	if protoimpl.UnsafeEnabled {
		mi := &file_origin_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Value_Add) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value_Add) ProtoMessage() {}

func (x *Value_Add) ProtoReflect() protoreflect.Message {
	mi := &file_origin_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value_Add.ProtoReflect.Descriptor instead.
func (*Value_Add) Descriptor() ([]byte, []int) {
	return file_origin_proto_rawDescGZIP(), []int{0, 4}
}

func (x *Value_Add) GetType() Value_Add_Type {
	if x != nil {
		return x.Type
	}
	return Value_Add_STRING
}

func (x *Value_Add) GetValues() []*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

// Typecast.
type Value_Cast struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  Value_Cast_Type `protobuf:"varint,101,opt,name=type,proto3,enum=jsonhttp.Value_Cast_Type" json:"type,omitempty"`
	Value *Value          `protobuf:"bytes,102,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Value_Cast) Reset() {
	*x = Value_Cast{}
	if protoimpl.UnsafeEnabled {
		mi := &file_origin_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Value_Cast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value_Cast) ProtoMessage() {}

func (x *Value_Cast) ProtoReflect() protoreflect.Message {
	mi := &file_origin_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value_Cast.ProtoReflect.Descriptor instead.
func (*Value_Cast) Descriptor() ([]byte, []int) {
	return file_origin_proto_rawDescGZIP(), []int{0, 5}
}

func (x *Value_Cast) GetType() Value_Cast_Type {
	if x != nil {
		return x.Type
	}
	return Value_Cast_BOOL
}

func (x *Value_Cast) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type Value_List struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []*Value `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *Value_List) Reset() {
	*x = Value_List{}
	if protoimpl.UnsafeEnabled {
		mi := &file_origin_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Value_List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value_List) ProtoMessage() {}

func (x *Value_List) ProtoReflect() protoreflect.Message {
	mi := &file_origin_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value_List.ProtoReflect.Descriptor instead.
func (*Value_List) Descriptor() ([]byte, []int) {
	return file_origin_proto_rawDescGZIP(), []int{0, 6}
}

func (x *Value_List) GetValues() []*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

type Value_Map struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values map[string]*Value `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Value_Map) Reset() {
	*x = Value_Map{}
	if protoimpl.UnsafeEnabled {
		mi := &file_origin_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Value_Map) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value_Map) ProtoMessage() {}

func (x *Value_Map) ProtoReflect() protoreflect.Message {
	mi := &file_origin_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value_Map.ProtoReflect.Descriptor instead.
func (*Value_Map) Descriptor() ([]byte, []int) {
	return file_origin_proto_rawDescGZIP(), []int{0, 7}
}

func (x *Value_Map) GetValues() map[string]*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

// Path of url.
type Value_Url_Path struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Index of the part of path separated by /.
	//
	// # Examples
	//
	// For /a/b,
	// index 0 means a, index 1 means b, other indexes are out of range.
	Index int32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (x *Value_Url_Path) Reset() {
	*x = Value_Url_Path{}
	if protoimpl.UnsafeEnabled {
		mi := &file_origin_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Value_Url_Path) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value_Url_Path) ProtoMessage() {}

func (x *Value_Url_Path) ProtoReflect() protoreflect.Message {
	mi := &file_origin_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value_Url_Path.ProtoReflect.Descriptor instead.
func (*Value_Url_Path) Descriptor() ([]byte, []int) {
	return file_origin_proto_rawDescGZIP(), []int{0, 2, 0}
}

func (x *Value_Url_Path) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

// Query of url.
type Value_Url_Query struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Query key.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *Value_Url_Query) Reset() {
	*x = Value_Url_Query{}
	if protoimpl.UnsafeEnabled {
		mi := &file_origin_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Value_Url_Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value_Url_Query) ProtoMessage() {}

func (x *Value_Url_Query) ProtoReflect() protoreflect.Message {
	mi := &file_origin_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value_Url_Query.ProtoReflect.Descriptor instead.
func (*Value_Url_Query) Descriptor() ([]byte, []int) {
	return file_origin_proto_rawDescGZIP(), []int{0, 2, 1}
}

func (x *Value_Url_Query) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// Current time.
type Value_Util_Now struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type Value_Util_Now_Type `protobuf:"varint,101,opt,name=type,proto3,enum=jsonhttp.Value_Util_Now_Type" json:"type,omitempty"`
}

func (x *Value_Util_Now) Reset() {
	*x = Value_Util_Now{}
	if protoimpl.UnsafeEnabled {
		mi := &file_origin_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Value_Util_Now) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value_Util_Now) ProtoMessage() {}

func (x *Value_Util_Now) ProtoReflect() protoreflect.Message {
	mi := &file_origin_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value_Util_Now.ProtoReflect.Descriptor instead.
func (*Value_Util_Now) Descriptor() ([]byte, []int) {
	return file_origin_proto_rawDescGZIP(), []int{0, 3, 0}
}

func (x *Value_Util_Now) GetType() Value_Util_Now_Type {
	if x != nil {
		return x.Type
	}
	return Value_Util_Now_TIMESTAMP
}

// Random data.
type Value_Util_Random struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Value:
	//	*Value_Util_Random_Type_
	//	*Value_Util_Random_Dice_
	Value isValue_Util_Random_Value `protobuf_oneof:"value"`
}

func (x *Value_Util_Random) Reset() {
	*x = Value_Util_Random{}
	if protoimpl.UnsafeEnabled {
		mi := &file_origin_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Value_Util_Random) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value_Util_Random) ProtoMessage() {}

func (x *Value_Util_Random) ProtoReflect() protoreflect.Message {
	mi := &file_origin_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value_Util_Random.ProtoReflect.Descriptor instead.
func (*Value_Util_Random) Descriptor() ([]byte, []int) {
	return file_origin_proto_rawDescGZIP(), []int{0, 3, 1}
}

func (m *Value_Util_Random) GetValue() isValue_Util_Random_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *Value_Util_Random) GetType() Value_Util_Random_Type {
	if x, ok := x.GetValue().(*Value_Util_Random_Type_); ok {
		return x.Type
	}
	return Value_Util_Random_UUID
}

func (x *Value_Util_Random) GetDice() *Value_Util_Random_Dice {
	if x, ok := x.GetValue().(*Value_Util_Random_Dice_); ok {
		return x.Dice
	}
	return nil
}

type isValue_Util_Random_Value interface {
	isValue_Util_Random_Value()
}

type Value_Util_Random_Type_ struct {
	Type Value_Util_Random_Type `protobuf:"varint,101,opt,name=type,proto3,enum=jsonhttp.Value_Util_Random_Type,oneof"`
}

type Value_Util_Random_Dice_ struct {
	Dice *Value_Util_Random_Dice `protobuf:"bytes,102,opt,name=dice,proto3,oneof"`
}

func (*Value_Util_Random_Type_) isValue_Util_Random_Value() {}

func (*Value_Util_Random_Dice_) isValue_Util_Random_Value() {}

// Random integer.
type Value_Util_Random_Dice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Min int32 `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	Max int32 `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
}

func (x *Value_Util_Random_Dice) Reset() {
	*x = Value_Util_Random_Dice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_origin_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Value_Util_Random_Dice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value_Util_Random_Dice) ProtoMessage() {}

func (x *Value_Util_Random_Dice) ProtoReflect() protoreflect.Message {
	mi := &file_origin_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value_Util_Random_Dice.ProtoReflect.Descriptor instead.
func (*Value_Util_Random_Dice) Descriptor() ([]byte, []int) {
	return file_origin_proto_rawDescGZIP(), []int{0, 3, 1, 0}
}

func (x *Value_Util_Random_Dice) GetMin() int32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *Value_Util_Random_Dice) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

// Wraps request.
type Action_Gateway struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path       *Value     `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	MethodType MethodType `protobuf:"varint,2,opt,name=methodType,proto3,enum=jsonhttp.MethodType" json:"methodType,omitempty"`
	// Request timeout(millisecond).
	Timeout              *Value              `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Templates            []*Template         `protobuf:"bytes,4,rep,name=templates,proto3" json:"templates,omitempty"`
	ResponseTemplates    []*Template         `protobuf:"bytes,5,rep,name=responseTemplates,proto3" json:"responseTemplates,omitempty"`
	TemplateType         Action_TemplateType `protobuf:"varint,6,opt,name=templateType,proto3,enum=jsonhttp.Action_TemplateType" json:"templateType,omitempty"`
	ResponseTemplateType Action_TemplateType `protobuf:"varint,7,opt,name=responseTemplateType,proto3,enum=jsonhttp.Action_TemplateType" json:"responseTemplateType,omitempty"`
}

func (x *Action_Gateway) Reset() {
	*x = Action_Gateway{}
	if protoimpl.UnsafeEnabled {
		mi := &file_origin_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action_Gateway) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action_Gateway) ProtoMessage() {}

func (x *Action_Gateway) ProtoReflect() protoreflect.Message {
	mi := &file_origin_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action_Gateway.ProtoReflect.Descriptor instead.
func (*Action_Gateway) Descriptor() ([]byte, []int) {
	return file_origin_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Action_Gateway) GetPath() *Value {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *Action_Gateway) GetMethodType() MethodType {
	if x != nil {
		return x.MethodType
	}
	return MethodType_GET
}

func (x *Action_Gateway) GetTimeout() *Value {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *Action_Gateway) GetTemplates() []*Template {
	if x != nil {
		return x.Templates
	}
	return nil
}

func (x *Action_Gateway) GetResponseTemplates() []*Template {
	if x != nil {
		return x.ResponseTemplates
	}
	return nil
}

func (x *Action_Gateway) GetTemplateType() Action_TemplateType {
	if x != nil {
		return x.TemplateType
	}
	return Action_SELECT
}

func (x *Action_Gateway) GetResponseTemplateType() Action_TemplateType {
	if x != nil {
		return x.ResponseTemplateType
	}
	return Action_SELECT
}

// Return response.
type Action_Return struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Templates []*Template `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	// Response status.
	Status int32 `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	// Delay response(millisecond).
	Delay        *Value              `protobuf:"bytes,3,opt,name=delay,proto3" json:"delay,omitempty"`
	TemplateType Action_TemplateType `protobuf:"varint,4,opt,name=templateType,proto3,enum=jsonhttp.Action_TemplateType" json:"templateType,omitempty"`
}

func (x *Action_Return) Reset() {
	*x = Action_Return{}
	if protoimpl.UnsafeEnabled {
		mi := &file_origin_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action_Return) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action_Return) ProtoMessage() {}

func (x *Action_Return) ProtoReflect() protoreflect.Message {
	mi := &file_origin_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action_Return.ProtoReflect.Descriptor instead.
func (*Action_Return) Descriptor() ([]byte, []int) {
	return file_origin_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Action_Return) GetTemplates() []*Template {
	if x != nil {
		return x.Templates
	}
	return nil
}

func (x *Action_Return) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Action_Return) GetDelay() *Value {
	if x != nil {
		return x.Delay
	}
	return nil
}

func (x *Action_Return) GetTemplateType() Action_TemplateType {
	if x != nil {
		return x.TemplateType
	}
	return Action_SELECT
}

var File_origin_proto protoreflect.FileDescriptor

var file_origin_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08,
	0x6a, 0x73, 0x6f, 0x6e, 0x68, 0x74, 0x74, 0x70, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x96, 0x0d, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x30, 0x0a, 0x04, 0x6e, 0x75, 0x6c, 0x6c, 0x18, 0x64, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x48, 0x00, 0x52, 0x04, 0x6e, 0x75,
	0x6c, 0x6c, 0x12, 0x0e, 0x0a, 0x01, 0x62, 0x18, 0x65, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52,
	0x01, 0x62, 0x12, 0x0e, 0x0a, 0x01, 0x6e, 0x18, 0x66, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52,
	0x01, 0x6e, 0x12, 0x0e, 0x0a, 0x01, 0x73, 0x18, 0x67, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x01, 0x73, 0x12, 0x24, 0x0a, 0x01, 0x6c, 0x18, 0x68, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x6a, 0x73, 0x6f, 0x6e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x48, 0x00, 0x52, 0x01, 0x6c, 0x12, 0x23, 0x0a, 0x01, 0x6d, 0x18, 0x69, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6a, 0x73, 0x6f, 0x6e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x2e, 0x4d, 0x61, 0x70, 0x48, 0x00, 0x52, 0x01, 0x6d, 0x12, 0x30, 0x0a,
	0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x6a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x6a, 0x73, 0x6f, 0x6e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x48, 0x00, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12,
	0x2a, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x6b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x6a, 0x73, 0x6f, 0x6e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x42,
	0x6f, 0x64, 0x79, 0x48, 0x00, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x27, 0x0a, 0x03, 0x75,
	0x72, 0x6c, 0x18, 0x6c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6a, 0x73, 0x6f, 0x6e, 0x68,
	0x74, 0x74, 0x70, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x55, 0x72, 0x6c, 0x48, 0x00, 0x52,
	0x03, 0x75, 0x72, 0x6c, 0x12, 0x2a, 0x0a, 0x04, 0x75, 0x74, 0x69, 0x6c, 0x18, 0x6d, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6a, 0x73, 0x6f, 0x6e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x2e, 0x55, 0x74, 0x69, 0x6c, 0x48, 0x00, 0x52, 0x04, 0x75, 0x74, 0x69, 0x6c,
	0x12, 0x27, 0x0a, 0x03, 0x61, 0x64, 0x64, 0x18, 0x6e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x6a, 0x73, 0x6f, 0x6e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x41,
	0x64, 0x64, 0x48, 0x00, 0x52, 0x03, 0x61, 0x64, 0x64, 0x12, 0x2a, 0x0a, 0x04, 0x63, 0x61, 0x73,
	0x74, 0x18, 0x6f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6a, 0x73, 0x6f, 0x6e, 0x68, 0x74,
	0x74, 0x70, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x43, 0x61, 0x73, 0x74, 0x48, 0x00, 0x52,
	0x04, 0x63, 0x61, 0x73, 0x74, 0x1a, 0x1a, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x1a, 0x1a, 0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x1a, 0xbd, 0x02,
	0x0a, 0x03, 0x55, 0x72, 0x6c, 0x12, 0x2e, 0x0a, 0x04, 0x70, 0x61, 0x72, 0x74, 0x18, 0x65, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x6a, 0x73, 0x6f, 0x6e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x2e, 0x55, 0x72, 0x6c, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x48, 0x00, 0x52,
	0x04, 0x70, 0x61, 0x72, 0x74, 0x12, 0x31, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x66,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6a, 0x73, 0x6f, 0x6e, 0x68, 0x74, 0x74, 0x70, 0x2e,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x55, 0x72, 0x6c, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x48,
	0x00, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x2e, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68,
	0x18, 0x67, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6a, 0x73, 0x6f, 0x6e, 0x68, 0x74, 0x74,
	0x70, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x55, 0x72, 0x6c, 0x2e, 0x50, 0x61, 0x74, 0x68,
	0x48, 0x00, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x1a, 0x1c, 0x0a, 0x04, 0x50, 0x61, 0x74, 0x68,
	0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x1a, 0x19, 0x0a, 0x05, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x22, 0x61, 0x0a, 0x04, 0x50, 0x61, 0x72, 0x74, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x43, 0x48,
	0x45, 0x4d, 0x45, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x55, 0x54, 0x48, 0x4f, 0x52, 0x49,
	0x54, 0x59, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x48, 0x4f, 0x53, 0x54, 0x10, 0x02, 0x12, 0x08,
	0x0a, 0x04, 0x50, 0x4f, 0x52, 0x54, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x41, 0x54, 0x48,
	0x10, 0x04, 0x12, 0x09, 0x0a, 0x05, 0x51, 0x55, 0x45, 0x52, 0x59, 0x10, 0x05, 0x12, 0x0c, 0x0a,
	0x08, 0x46, 0x52, 0x41, 0x47, 0x4d, 0x45, 0x4e, 0x54, 0x10, 0x06, 0x12, 0x07, 0x0a, 0x03, 0x41,
	0x4c, 0x4c, 0x10, 0x07, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x91, 0x03,
	0x0a, 0x04, 0x55, 0x74, 0x69, 0x6c, 0x12, 0x2c, 0x0a, 0x03, 0x6e, 0x6f, 0x77, 0x18, 0x65, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6a, 0x73, 0x6f, 0x6e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x2e, 0x55, 0x74, 0x69, 0x6c, 0x2e, 0x4e, 0x6f, 0x77, 0x48, 0x00, 0x52,
	0x03, 0x6e, 0x6f, 0x77, 0x12, 0x35, 0x0a, 0x06, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x18, 0x66,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6a, 0x73, 0x6f, 0x6e, 0x68, 0x74, 0x74, 0x70, 0x2e,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x55, 0x74, 0x69, 0x6c, 0x2e, 0x52, 0x61, 0x6e, 0x64, 0x6f,
	0x6d, 0x48, 0x00, 0x52, 0x06, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x1a, 0x4f, 0x0a, 0x03, 0x4e,
	0x6f, 0x77, 0x12, 0x31, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x65, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x1d, 0x2e, 0x6a, 0x73, 0x6f, 0x6e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x2e, 0x55, 0x74, 0x69, 0x6c, 0x2e, 0x4e, 0x6f, 0x77, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x15, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a,
	0x09, 0x54, 0x49, 0x4d, 0x45, 0x53, 0x54, 0x41, 0x4d, 0x50, 0x10, 0x00, 0x1a, 0xc9, 0x01, 0x0a,
	0x06, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x12, 0x36, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x65, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x6a, 0x73, 0x6f, 0x6e, 0x68, 0x74, 0x74, 0x70,
	0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x55, 0x74, 0x69, 0x6c, 0x2e, 0x52, 0x61, 0x6e, 0x64,
	0x6f, 0x6d, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x48, 0x00, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x36, 0x0a, 0x04, 0x64, 0x69, 0x63, 0x65, 0x18, 0x66, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e,
	0x6a, 0x73, 0x6f, 0x6e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x55,
	0x74, 0x69, 0x6c, 0x2e, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x2e, 0x44, 0x69, 0x63, 0x65, 0x48,
	0x00, 0x52, 0x04, 0x64, 0x69, 0x63, 0x65, 0x1a, 0x2a, 0x0a, 0x04, 0x44, 0x69, 0x63, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6d, 0x69,
	0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x6d, 0x61, 0x78, 0x22, 0x1a, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x55,
	0x55, 0x49, 0x44, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x54, 0x44, 0x55, 0x10, 0x01, 0x42,
	0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x1a, 0x7c, 0x0a, 0x03, 0x41, 0x64, 0x64, 0x12, 0x2c, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x65, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x6a, 0x73, 0x6f, 0x6e, 0x68, 0x74, 0x74,
	0x70, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x2e, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x27, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73,
	0x18, 0x66, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6a, 0x73, 0x6f, 0x6e, 0x68, 0x74, 0x74,
	0x70, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22,
	0x1e, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x54, 0x52, 0x49, 0x4e,
	0x47, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x55, 0x4d, 0x42, 0x45, 0x52, 0x10, 0x01, 0x1a,
	0x86, 0x01, 0x0a, 0x04, 0x43, 0x61, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x65, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x6a, 0x73, 0x6f, 0x6e, 0x68, 0x74, 0x74,
	0x70, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x43, 0x61, 0x73, 0x74, 0x2e, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x25, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x66, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6a, 0x73, 0x6f, 0x6e, 0x68, 0x74, 0x74,
	0x70, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x28,
	0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x42, 0x4f, 0x4f, 0x4c, 0x10, 0x00,
	0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x55, 0x4d, 0x42, 0x45, 0x52, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06,
	0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x1a, 0x2f, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x27, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x6a, 0x73, 0x6f, 0x6e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x1a, 0x8a, 0x01, 0x0a, 0x03, 0x4d, 0x61,
	0x70, 0x12, 0x37, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1f, 0x2e, 0x6a, 0x73, 0x6f, 0x6e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x2e, 0x4d, 0x61, 0x70, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x1a, 0x4a, 0x0a, 0x0b, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x25, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6a, 0x73, 0x6f,
	0x6e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0x7c, 0x0a, 0x08, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x2b, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x65, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x6a, 0x73, 0x6f, 0x6e,
	0x68, 0x74, 0x74, 0x70, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x2e, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x25, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x66, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6a, 0x73, 0x6f, 0x6e, 0x68, 0x74,
	0x74, 0x70, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0x1c, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x42, 0x4f, 0x44, 0x59, 0x10,
	0x00, 0x12, 0x0a, 0x0a, 0x06, 0x48, 0x45, 0x41, 0x44, 0x45, 0x52, 0x10, 0x01, 0x22, 0xfe, 0x05,
	0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x31, 0x0a, 0x06, 0x72, 0x65, 0x74, 0x75,
	0x72, 0x6e, 0x18, 0x65, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6a, 0x73, 0x6f, 0x6e, 0x68,
	0x74, 0x74, 0x70, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x74, 0x75, 0x72,
	0x6e, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x12, 0x34, 0x0a, 0x07, 0x67,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x18, 0x66, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6a,
	0x73, 0x6f, 0x6e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x47,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x48, 0x00, 0x52, 0x07, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x1a, 0x99, 0x03, 0x0a, 0x07, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x12, 0x23, 0x0a,
	0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6a, 0x73,
	0x6f, 0x6e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x12, 0x34, 0x0a, 0x0a, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x6a, 0x73, 0x6f, 0x6e, 0x68, 0x74, 0x74,
	0x70, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x6d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x29, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65,
	0x6f, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6a, 0x73, 0x6f, 0x6e,
	0x68, 0x74, 0x74, 0x70, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65,
	0x6f, 0x75, 0x74, 0x12, 0x30, 0x0a, 0x09, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6a, 0x73, 0x6f, 0x6e, 0x68, 0x74, 0x74,
	0x70, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x09, 0x74, 0x65, 0x6d, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x73, 0x12, 0x40, 0x0a, 0x11, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x6a, 0x73, 0x6f, 0x6e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x54, 0x65, 0x6d, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x52, 0x11, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x12, 0x41, 0x0a, 0x0c, 0x74, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e,
	0x6a, 0x73, 0x6f, 0x6e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0c, 0x74, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x51, 0x0a, 0x14, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x6a, 0x73, 0x6f, 0x6e, 0x68,
	0x74, 0x74, 0x70, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x14, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x1a, 0xbc, 0x01,
	0x0a, 0x06, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x12, 0x30, 0x0a, 0x09, 0x74, 0x65, 0x6d, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6a, 0x73,
	0x6f, 0x6e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52,
	0x09, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x25, 0x0a, 0x05, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x6a, 0x73, 0x6f, 0x6e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x52, 0x05, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x12, 0x41, 0x0a, 0x0c, 0x74, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x1d, 0x2e, 0x6a, 0x73, 0x6f, 0x6e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0c,
	0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x26, 0x0a, 0x0c,
	0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06,
	0x53, 0x45, 0x4c, 0x45, 0x43, 0x54, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x50, 0x50, 0x45,
	0x4e, 0x44, 0x10, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x7d,
	0x0a, 0x07, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x34, 0x0a,
	0x0a, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x14, 0x2e, 0x6a, 0x73, 0x6f, 0x6e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x4d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x28, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6a, 0x73, 0x6f, 0x6e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x4b, 0x0a,
	0x06, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x2d, 0x0a, 0x08, 0x68,
	0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x6a, 0x73, 0x6f, 0x6e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72,
	0x52, 0x08, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x73, 0x2a, 0x1f, 0x0a, 0x0a, 0x4d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x47, 0x45, 0x54, 0x10,
	0x00, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x4f, 0x53, 0x54, 0x10, 0x01, 0x42, 0x23, 0x5a, 0x21, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x65, 0x72, 0x71, 0x75, 0x65,
	0x72, 0x61, 0x6e, 0x74, 0x2f, 0x6a, 0x73, 0x6f, 0x6e, 0x68, 0x74, 0x74, 0x70, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_origin_proto_rawDescOnce sync.Once
	file_origin_proto_rawDescData = file_origin_proto_rawDesc
)

func file_origin_proto_rawDescGZIP() []byte {
	file_origin_proto_rawDescOnce.Do(func() {
		file_origin_proto_rawDescData = protoimpl.X.CompressGZIP(file_origin_proto_rawDescData)
	})
	return file_origin_proto_rawDescData
}

var file_origin_proto_enumTypes = make([]protoimpl.EnumInfo, 8)
var file_origin_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_origin_proto_goTypes = []interface{}{
	(MethodType)(0),                // 0: jsonhttp.MethodType
	(Value_Url_Part)(0),            // 1: jsonhttp.Value.Url.Part
	(Value_Util_Now_Type)(0),       // 2: jsonhttp.Value.Util.Now.Type
	(Value_Util_Random_Type)(0),    // 3: jsonhttp.Value.Util.Random.Type
	(Value_Add_Type)(0),            // 4: jsonhttp.Value.Add.Type
	(Value_Cast_Type)(0),           // 5: jsonhttp.Value.Cast.Type
	(Template_Type)(0),             // 6: jsonhttp.Template.Type
	(Action_TemplateType)(0),       // 7: jsonhttp.Action.TemplateType
	(*Value)(nil),                  // 8: jsonhttp.Value
	(*Template)(nil),               // 9: jsonhttp.Template
	(*Action)(nil),                 // 10: jsonhttp.Action
	(*Handler)(nil),                // 11: jsonhttp.Handler
	(*Server)(nil),                 // 12: jsonhttp.Server
	(*Value_Header)(nil),           // 13: jsonhttp.Value.Header
	(*Value_Body)(nil),             // 14: jsonhttp.Value.Body
	(*Value_Url)(nil),              // 15: jsonhttp.Value.Url
	(*Value_Util)(nil),             // 16: jsonhttp.Value.Util
	(*Value_Add)(nil),              // 17: jsonhttp.Value.Add
	(*Value_Cast)(nil),             // 18: jsonhttp.Value.Cast
	(*Value_List)(nil),             // 19: jsonhttp.Value.List
	(*Value_Map)(nil),              // 20: jsonhttp.Value.Map
	(*Value_Url_Path)(nil),         // 21: jsonhttp.Value.Url.Path
	(*Value_Url_Query)(nil),        // 22: jsonhttp.Value.Url.Query
	(*Value_Util_Now)(nil),         // 23: jsonhttp.Value.Util.Now
	(*Value_Util_Random)(nil),      // 24: jsonhttp.Value.Util.Random
	(*Value_Util_Random_Dice)(nil), // 25: jsonhttp.Value.Util.Random.Dice
	nil,                            // 26: jsonhttp.Value.Map.ValuesEntry
	(*Action_Gateway)(nil),         // 27: jsonhttp.Action.Gateway
	(*Action_Return)(nil),          // 28: jsonhttp.Action.Return
	(structpb.NullValue)(0),        // 29: google.protobuf.NullValue
}
var file_origin_proto_depIdxs = []int32{
	29, // 0: jsonhttp.Value.null:type_name -> google.protobuf.NullValue
	19, // 1: jsonhttp.Value.l:type_name -> jsonhttp.Value.List
	20, // 2: jsonhttp.Value.m:type_name -> jsonhttp.Value.Map
	13, // 3: jsonhttp.Value.header:type_name -> jsonhttp.Value.Header
	14, // 4: jsonhttp.Value.body:type_name -> jsonhttp.Value.Body
	15, // 5: jsonhttp.Value.url:type_name -> jsonhttp.Value.Url
	16, // 6: jsonhttp.Value.util:type_name -> jsonhttp.Value.Util
	17, // 7: jsonhttp.Value.add:type_name -> jsonhttp.Value.Add
	18, // 8: jsonhttp.Value.cast:type_name -> jsonhttp.Value.Cast
	6,  // 9: jsonhttp.Template.type:type_name -> jsonhttp.Template.Type
	8,  // 10: jsonhttp.Template.value:type_name -> jsonhttp.Value
	28, // 11: jsonhttp.Action.return:type_name -> jsonhttp.Action.Return
	27, // 12: jsonhttp.Action.gateway:type_name -> jsonhttp.Action.Gateway
	0,  // 13: jsonhttp.Handler.methodType:type_name -> jsonhttp.MethodType
	10, // 14: jsonhttp.Handler.action:type_name -> jsonhttp.Action
	11, // 15: jsonhttp.Server.handlers:type_name -> jsonhttp.Handler
	1,  // 16: jsonhttp.Value.Url.part:type_name -> jsonhttp.Value.Url.Part
	22, // 17: jsonhttp.Value.Url.query:type_name -> jsonhttp.Value.Url.Query
	21, // 18: jsonhttp.Value.Url.path:type_name -> jsonhttp.Value.Url.Path
	23, // 19: jsonhttp.Value.Util.now:type_name -> jsonhttp.Value.Util.Now
	24, // 20: jsonhttp.Value.Util.random:type_name -> jsonhttp.Value.Util.Random
	4,  // 21: jsonhttp.Value.Add.type:type_name -> jsonhttp.Value.Add.Type
	8,  // 22: jsonhttp.Value.Add.values:type_name -> jsonhttp.Value
	5,  // 23: jsonhttp.Value.Cast.type:type_name -> jsonhttp.Value.Cast.Type
	8,  // 24: jsonhttp.Value.Cast.value:type_name -> jsonhttp.Value
	8,  // 25: jsonhttp.Value.List.values:type_name -> jsonhttp.Value
	26, // 26: jsonhttp.Value.Map.values:type_name -> jsonhttp.Value.Map.ValuesEntry
	2,  // 27: jsonhttp.Value.Util.Now.type:type_name -> jsonhttp.Value.Util.Now.Type
	3,  // 28: jsonhttp.Value.Util.Random.type:type_name -> jsonhttp.Value.Util.Random.Type
	25, // 29: jsonhttp.Value.Util.Random.dice:type_name -> jsonhttp.Value.Util.Random.Dice
	8,  // 30: jsonhttp.Value.Map.ValuesEntry.value:type_name -> jsonhttp.Value
	8,  // 31: jsonhttp.Action.Gateway.path:type_name -> jsonhttp.Value
	0,  // 32: jsonhttp.Action.Gateway.methodType:type_name -> jsonhttp.MethodType
	8,  // 33: jsonhttp.Action.Gateway.timeout:type_name -> jsonhttp.Value
	9,  // 34: jsonhttp.Action.Gateway.templates:type_name -> jsonhttp.Template
	9,  // 35: jsonhttp.Action.Gateway.responseTemplates:type_name -> jsonhttp.Template
	7,  // 36: jsonhttp.Action.Gateway.templateType:type_name -> jsonhttp.Action.TemplateType
	7,  // 37: jsonhttp.Action.Gateway.responseTemplateType:type_name -> jsonhttp.Action.TemplateType
	9,  // 38: jsonhttp.Action.Return.templates:type_name -> jsonhttp.Template
	8,  // 39: jsonhttp.Action.Return.delay:type_name -> jsonhttp.Value
	7,  // 40: jsonhttp.Action.Return.templateType:type_name -> jsonhttp.Action.TemplateType
	41, // [41:41] is the sub-list for method output_type
	41, // [41:41] is the sub-list for method input_type
	41, // [41:41] is the sub-list for extension type_name
	41, // [41:41] is the sub-list for extension extendee
	0,  // [0:41] is the sub-list for field type_name
}

func init() { file_origin_proto_init() }
func file_origin_proto_init() {
	if File_origin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_origin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Value); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_origin_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Template); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_origin_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Action); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_origin_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Handler); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_origin_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Server); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_origin_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Value_Header); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_origin_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Value_Body); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_origin_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Value_Url); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_origin_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Value_Util); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_origin_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Value_Add); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_origin_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Value_Cast); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_origin_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Value_List); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_origin_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Value_Map); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_origin_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Value_Url_Path); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_origin_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Value_Url_Query); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_origin_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Value_Util_Now); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_origin_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Value_Util_Random); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_origin_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Value_Util_Random_Dice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_origin_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Action_Gateway); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_origin_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Action_Return); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_origin_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Value_Null)(nil),
		(*Value_B)(nil),
		(*Value_N)(nil),
		(*Value_S)(nil),
		(*Value_L)(nil),
		(*Value_M)(nil),
		(*Value_Header_)(nil),
		(*Value_Body_)(nil),
		(*Value_Url_)(nil),
		(*Value_Util_)(nil),
		(*Value_Add_)(nil),
		(*Value_Cast_)(nil),
	}
	file_origin_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*Action_Return_)(nil),
		(*Action_Gateway_)(nil),
	}
	file_origin_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*Value_Url_Part_)(nil),
		(*Value_Url_Query_)(nil),
		(*Value_Url_Path_)(nil),
	}
	file_origin_proto_msgTypes[8].OneofWrappers = []interface{}{
		(*Value_Util_Now_)(nil),
		(*Value_Util_Random_)(nil),
	}
	file_origin_proto_msgTypes[16].OneofWrappers = []interface{}{
		(*Value_Util_Random_Type_)(nil),
		(*Value_Util_Random_Dice_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_origin_proto_rawDesc,
			NumEnums:      8,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_origin_proto_goTypes,
		DependencyIndexes: file_origin_proto_depIdxs,
		EnumInfos:         file_origin_proto_enumTypes,
		MessageInfos:      file_origin_proto_msgTypes,
	}.Build()
	File_origin_proto = out.File
	file_origin_proto_rawDesc = nil
	file_origin_proto_goTypes = nil
	file_origin_proto_depIdxs = nil
}
